[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.check-alerts]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false
